global:
  domain: ukdcicd.niua.in ## Add your Domain Name Eg: site.mydomain.com
  setup: fullsetup
  
cluster-configs:
  namespaces:
    create: true
    values: [ jenkins, cert-manager ]
  root-ingress:
    namespace: jenkins
    serviceName: jenkins
    servicePort: 8080
    appRoot: ""
    cert-issuer: "letsencrypt-prod"

jenkins:
  persistence:
    enabled: true
    aws:
      - volumeId: "vol-0b55ceb9443447871" # Add volume id for jenkins-home
        zone: ap-south-1b # Add respective availability_zones 

  oauth:
    enabled: true
    acl:
      admin:
        - UKDJEN*ukdcicd # Add github team. Members of this team gets admin access on jenkins
      user:                                 # Add github team. Members of this team gets login access on jenkins
        - UKDJEN*ukdcicd-ci
        - UKDJEN*ukdcicd-qa
        - UKDJEN*ukdcicd-uat
       

  jobBuilder:    # Add jobBuilder repo's, add repo's ssh link
    repos: >-
      'https://github.com/UKDJEN/DIGIT-UKD.git','https://github.com/UKDJEN/UPYOG.git'
  deploymentJobs:  # Setup deploymentJobs ACL 
    - name: ci    # deployment job name
      acl: [UKDJEN*ukdcicd-ci] # GitHub team name, Members of the team get access to deployment job
    - name: qa
      acl: [UKDJEN*ukdcicd-qa] 
    - name: uat
      acl: [UKDJEN*ukdcicd-uat] 
    
       
  master:
    ingress:
      enabled: true
    resources:
      limits:
        cpu: "2000m"
        memory: "4096Mi"
    javaOpts: "-Xms2560M -Xmx2560M -Duser.timezone=Asia/Calcutta"

nginx-ingress:
  replicas: 1
  default-backend-service: "jenkins/jenkins"
  namespace: jenkins
  cert-issuer: "letsencrypt-staging"
  ssl-protocols: "TLSv1.2 TLSv1.3"
  ssl-ciphers: "EECDH+CHACHA20:EECDH+AES"
  ssl-ecdh-curve: "X25519:prime256v1:secp521r1:secp384r1"
  controller:
    image:
      repository: egovio/nginx-ingress-controller
      tag: "0.26.1"

cert-manager:
  namespace: jenkins
  clusterIssuer:
    stage:
      acme:
        email: "sahmed@niua.org"     # Add mail id

cluster-autoscaler:
  namespace: jenkins
  cloudProvider: aws  
  awsRegion: ap-south-1
  autoDiscovery:
    clusterName: ukd-cicd # Add cluster name
    tags:
    - kubernetes.io/cluster/ukd-cicd # Add cluster name
